services:
  hestia-sharp:
    image: hestia-sharp
    env_file: ".env"
    networks:
      - hestia-sharp-network
    build:
      context: .
      dockerfile: HestiaSharp/Dockerfile
    restart: unless-stopped

  hestia-sharp-bot:
    image: hestia-sharp-bot
    env_file: ".env"
    build:
      context: .
      dockerfile: HestiaSharpBot/Dockerfile
    networks:
      - hestia-sharp-network
    restart: unless-stopped

  hestia-sharp-database:
    container_name: hestia-sharp-database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: hestiasharp
      POSTGRES_USER: hestiasharp
      POSTGRES_DB: hestiasharp
    networks:
      - hestia-sharp-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - hestia-sharp-database:/var/lib/postgresql/data

networks:
  hestia-sharp-network:
    name: hestia-sharp-network

volumes:
  hestia-sharp-database:
